report:
  title: "TK Insight Report"
  author: "TK Reports"
  include_charts: true
  include_narrative: true
  export_formats: ["pdf", "docx"]
  locale: "en_CA"

openai:
  model: "gpt-4-turbo"
  temperature: 0.3
  max_tokens: 2000
